name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and push to GitHub Packages
      run: |
        VERSION=$(date +%s)
        REPO_NAME="${{ github.repository }}"
        LOWERCASE_REPO_NAME=${LOWERCASE_REPO_NAME,,}
        docker build ./services/sbus-queue-reader/ --file ./services/sbus-queue-reader/Dockerfile --tag docker.pkg.github.com/${LOWERCASE_REPO_NAME}/sbus-reader:${VERSION}
        docker login docker.pkg.github.com --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/${LOWERCASE_REPO_NAME}/sbus-reader:${VERSION}